project_id = "diqfthpfncdojlnqnicq"

[functions.errorreport-proxy]
verify_jwt = false

[functions.ivion-proxy]
verify_jwt = false

[functions.senslinc-query]
verify_jwt = false

[functions.asset-plus-delete]
verify_jwt = false

[functions.acc-sync]
verify_jwt = false

[functions.acc-auth]
verify_jwt = false

[functions.acc-to-assetplus]
verify_jwt = false

[functions.gunnar-chat]
verify_jwt = false

[functions.acc-svf-to-gltf]
verify_jwt = false

[functions.mobile-ai-scan]
verify_jwt = false