project_id = "diqfthpfncdojlnqnicq"

[functions.errorreport-proxy]
verify_jwt = false

[functions.ivion-proxy]
verify_jwt = false

[functions.senslinc-query]
verify_jwt = false

[functions.asset-plus-delete]
verify_jwt = false

[functions.acc-sync]
verify_jwt = false

[functions.acc-auth]
verify_jwt = false

[functions.acc-to-assetplus]
verify_jwt = false

[functions.gunnar-chat]
verify_jwt = false

[functions.acc-svf-to-gltf]
verify_jwt = false

[functions.mobile-ai-scan]
verify_jwt = false

[functions.asset-plus-create-building]
verify_jwt = false

[functions.asset-plus-create-hierarchy]
verify_jwt = false

[functions.send-issue-email]
verify_jwt = false

[functions.ifc-to-xkt]
verify_jwt = false

[functions.support-proxy]
verify_jwt = false

[functions.bim-to-gltf]
verify_jwt = false

[functions.bip-import]
verify_jwt = false

[functions.bip-classify]
verify_jwt = false

[functions.ifc-extract-systems]
verify_jwt = false

[functions.index-documents]
verify_jwt = false

[functions.feedback-notify]
verify_jwt = false

[functions.faciliate-proxy]
verify_jwt = false

[functions.fm-access-sync]
verify_jwt = false

[functions.imdf-export]
verify_jwt = false

[functions.conversion-worker-api]
verify_jwt = false

[functions.acc-geometry-extract]
verify_jwt = false

[functions.predictive-maintenance]
verify_jwt = false

[functions.rag-search]
verify_jwt = false

[functions.room-optimization]
verify_jwt = false

[functions.mapbox-directions]
verify_jwt = false

[functions.google-routes]
verify_jwt = false

[functions.rebuild-geometry-map]
verify_jwt = false

[functions.viewer-manifest]
verify_jwt = false

[functions.get-streetview-key]
verify_jwt = false

[functions.deepgram-token]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false