services:
  - type: web
    name: ifc-federation
    runtime: node
    rootDir: ifc-federation-app
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: GEMINUS_PLUS_KEYCLOAK_URL
        sync: false
      - key: GEMINUS_PLUS_CLIENT_ID
        sync: false
      - key: GEMINUS_PLUS_USERNAME
        sync: false
      - key: GEMINUS_PLUS_PASSWORD
        sync: false
      - key: GEMINUS_PLUS_API_URL
        sync: false
      - key: GEMINUS_PLUS_API_KEY
        sync: false
