INSERT INTO detection_templates (name, object_type, description, ai_prompt, default_category, is_active) VALUES
('Fire door', 'fire_door', 'Fire-rated door with self-closing mechanism', 'Look for fire-rated doors. They typically have a self-closing mechanism (door closer arm at the top), push bars or lever handles, and may have a small window with wire-reinforced glass. Often labeled with fire door keep shut signage.', 'Fire safety', true),
('Elevator', 'elevator', 'Elevator cab and corridor doors', 'Look for elevator doors in corridors or lobbies. They appear as pairs of metal doors (stainless steel or painted) flush with the wall, with a call button panel (up/down arrows or floor numbers) mounted beside them at about 1m height.', 'Transport systems', true),
('Escalator', 'escalator', 'Moving staircase for passenger transport', 'Look for escalators: moving staircases with metal or rubber steps, metal side panels, and rubber handrails on both sides that move with the steps. Usually found in shopping centers, airports, or large public buildings.', 'Transport systems', true),
('Moving walkway', 'moving_walkway', 'Horizontal conveyor for pedestrians', 'Look for moving walkways or travelators: flat or slightly inclined conveyor belts built into the floor for pedestrians, with rubber handrails on each side. Found in airports, large shopping malls, or transit hubs.', 'Transport systems', true),
('Fire alarm', 'fire_alarm', 'Fire alarm panel, pull stations and sounder units', 'Look for fire alarm devices mounted on walls: red pull-station boxes, alarm sounders, strobe lights, or smoke detector heads on ceilings. Usually red and often labeled with fire alarm text.', 'Fire safety', true),
('Sprinkler', 'sprinkler_head', 'Sprinkler heads in ceiling', 'Look for fire sprinkler heads mounted in ceilings. They are small devices with a glass bulb (often red, orange, or yellow) or a metal deflector plate. Often recessed or flush with ceiling tiles.', 'Fire safety', true),
('Emergency lighting', 'emergency_light', 'Emergency lighting fixtures', 'Look for emergency lighting units on walls or ceilings: battery-backed fixtures with one or two bright white or green lamps pointing forward. Often have a small LED test indicator.', 'Electrical and lighting', true),
('AED (defibrillator)', 'aed', 'Automated external defibrillator', 'Look for AED wall cabinets: typically green or red rectangular boxes mounted on walls at about 1.2-1.5m height, labeled AED, defibrillator, or hjärtstartare. May have a heart symbol or lightning bolt icon.', 'Safety', true);
